<?php
/**
 * Localized data
 *
 * @copyright Copyright (C) 2010-2018 Combodo SARL
 * @license    http://opensource.org/licenses/AGPL-3.0
 *
 * This file is part of iTop.
 *
 * iTop is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * iTop is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with iTop. If not, see <http://www.gnu.org/licenses/>
 */
 
  /**
 *
 * @author      Nazarenko Olexandr <olexandr.n@gmail.com>
 * @link        https://github.com/olexandrn/iTop
 * @license     http://opensource.org/licenses/AGPL-3.0
 *
 */


Dict::Add('uk ua', 'Ukraine', 'Українська', array(
	'Menu:RequestManagement' => 'Служба підтримки',
	'Menu:RequestManagement+' => 'Служба підтримки',
	'Menu:RequestManagementProvider' => 'Постачалник техпідтримки',
	'Menu:RequestManagementProvider+' => 'Постачалник техпідтримки',
	'Menu:UserRequest:Provider' => 'Відкриті запити, відправлені постачальнику',
	'Menu:UserRequest:Provider+' => 'Відкриті запити, відправлені постачальнику',
	'Menu:UserRequest:Overview' => 'Огляд',
	'Menu:UserRequest:Overview+' => 'Огляд',
	'Menu:NewUserRequest' => 'Новий запит',
	'Menu:NewUserRequest+' => 'Створити новий запит',
	'Menu:SearchUserRequests' => 'Пошук запиту',
	'Menu:SearchUserRequests+' => 'Пошук запиту',
	'Menu:UserRequest:Shortcuts' => 'Ярлики',
	'Menu:UserRequest:Shortcuts+' => '~~',
	'Menu:UserRequest:MyRequests' => 'Мені на виконання',
	'Menu:UserRequest:MyRequests+' => 'Мені на виконання',
	'Menu:UserRequest:MySupportRequests' => "Створені мною",
	'Menu:UserRequest:MySupportRequests+' => "Створені мною запити",
	'Menu:UserRequest:EscalatedRequests' => 'Потребують уваги',
	'Menu:UserRequest:EscalatedRequests+' => 'Ескальовані запити',
	'Menu:UserRequest:OpenRequests' => 'Усі відкриті запити',
	'Menu:UserRequest:OpenRequests+' => 'Усі відкриті запити',
	'UI:WelcomeMenu:MyAssignedCalls' => 'Запити мені на виконання',
	'UI-RequestManagementOverview-RequestByType-last-14-days' => 'Типи запитів за останні 14 днів',
	'UI-RequestManagementOverview-Last-14-days' => 'Кількість запитів за останні 14 днів',
	'UI-RequestManagementOverview-OpenRequestByStatus' => 'Відкриті запити за статусом',
	'UI-RequestManagementOverview-OpenRequestByAgent' => 'Відкриті запити за виконавцем',
	'UI-RequestManagementOverview-OpenRequestByType' => 'Відкриті запити за типом',
	'UI-RequestManagementOverview-OpenRequestByCustomer' => 'Відкриті запити за організацією',
	'Class:UserRequest:KnownErrorList' => 'Відомі помилки',
	'Menu:UserRequest:MyWorkOrders' => 'Робочі доручення, призначені мені',
	'Menu:UserRequest:MyWorkOrders+' => 'Робочі доручення, призначені мені',
	'Class:Problem:KnownProblemList' => 'Відомі проблеми',
	'Tickets:Related:OpenIncidents' => 'Відкриті інциденти',
));

// Dictionnay conventions
// Class:<class_name>
// Class:<class_name>+
// Class:<class_name>/Attribute:<attribute_code>
// Class:<class_name>/Attribute:<attribute_code>+
// Class:<class_name>/Attribute:<attribute_code>/Value:<value>
// Class:<class_name>/Attribute:<attribute_code>/Value:<value>+
// Class:<class_name>/Stimulus:<stimulus_code>
// Class:<class_name>/Stimulus:<stimulus_code>+

//
// Class: UserRequest
//

Dict::Add('uk ua', 'Ukraine', 'Українська', array(
	'Class:UserRequest' => 'Запит',
	'Class:UserRequest+' => '~~',
	'Class:UserRequest/Attribute:status' => 'Статус',
	'Class:UserRequest/Attribute:status+' => '~~',
	'Class:UserRequest/Attribute:status/Value:new' => 'Новий',
	'Class:UserRequest/Attribute:status/Value:new+' => '~~',
	'Class:UserRequest/Attribute:status/Value:escalated_tto' => 'Перевищення TTO',
	'Class:UserRequest/Attribute:status/Value:escalated_tto+' => 'Перевищення часу призначення виконавця',
	'Class:UserRequest/Attribute:status/Value:assigned' => 'На виконанні',
	'Class:UserRequest/Attribute:status/Value:assigned+' => '~~',
	'Class:UserRequest/Attribute:status/Value:escalated_ttr' => 'Перевищення TTR',
	'Class:UserRequest/Attribute:status/Value:escalated_ttr+' => 'Перевищення часу виконання запиту',
	'Class:UserRequest/Attribute:status/Value:waiting_for_approval' => 'На погодженні',
	'Class:UserRequest/Attribute:status/Value:waiting_for_approval+' => '~~',
	'Class:UserRequest/Attribute:status/Value:approved' => 'Погоджений',
	'Class:UserRequest/Attribute:status/Value:approved+' => '~~',
	'Class:UserRequest/Attribute:status/Value:rejected' => 'Відхилений',
	'Class:UserRequest/Attribute:status/Value:rejected+' => '~~',
	'Class:UserRequest/Attribute:status/Value:pending' => 'Призупинений',
	'Class:UserRequest/Attribute:status/Value:pending+' => '~~',
	'Class:UserRequest/Attribute:status/Value:resolved' => 'Виконаний',
	'Class:UserRequest/Attribute:status/Value:resolved+' => '~~',
	'Class:UserRequest/Attribute:status/Value:closed' => 'Закритий',
	'Class:UserRequest/Attribute:status/Value:closed+' => '~~',
	'Class:UserRequest/Attribute:request_type' => 'Тип запиту',
	'Class:UserRequest/Attribute:request_type+' => '~~',
	'Class:UserRequest/Attribute:request_type/Value:incident' => 'Інцидент',
	'Class:UserRequest/Attribute:request_type/Value:incident+' => 'Подія, збій, що не є частиною нормального функціонування процесу',
	'Class:UserRequest/Attribute:request_type/Value:service_request' => 'Запит на обслуговування',
	'Class:UserRequest/Attribute:request_type/Value:service_request+' => 'Запит на стандартну зміну, доступ, отримання інформації, або консультацію',
	'Class:UserRequest/Attribute:impact' => 'Рівень впливу',
	'Class:UserRequest/Attribute:impact+' => '~~',
	'Class:UserRequest/Attribute:impact/Value:1' => 'Департамент',
	'Class:UserRequest/Attribute:impact/Value:1+' => '~~',
	'Class:UserRequest/Attribute:impact/Value:2' => 'Сервіс',
	'Class:UserRequest/Attribute:impact/Value:2+' => '~~',
	'Class:UserRequest/Attribute:impact/Value:3' => 'Користувач',
	'Class:UserRequest/Attribute:impact/Value:3+' => '~~',
	'Class:UserRequest/Attribute:priority' => 'Пріоритет',
	'Class:UserRequest/Attribute:priority+' => '~~',
	'Class:UserRequest/Attribute:priority/Value:1' => 'Критичний',
	'Class:UserRequest/Attribute:priority/Value:1+' => 'Критичний',
	'Class:UserRequest/Attribute:priority/Value:2' => 'Високий',
	'Class:UserRequest/Attribute:priority/Value:2+' => 'Високий',
	'Class:UserRequest/Attribute:priority/Value:3' => 'Середній',
	'Class:UserRequest/Attribute:priority/Value:3+' => 'Середній',
	'Class:UserRequest/Attribute:priority/Value:4' => 'Низький',
	'Class:UserRequest/Attribute:priority/Value:4+' => 'Низький',
	'Class:UserRequest/Attribute:urgency' => 'Терміновість',
	'Class:UserRequest/Attribute:urgency+' => '~~',
	'Class:UserRequest/Attribute:urgency/Value:1' => 'Критична',
	'Class:UserRequest/Attribute:urgency/Value:1+' => 'Критична',
	'Class:UserRequest/Attribute:urgency/Value:2' => 'Висока',
	'Class:UserRequest/Attribute:urgency/Value:2+' => 'Висока',
	'Class:UserRequest/Attribute:urgency/Value:3' => 'Середня',
	'Class:UserRequest/Attribute:urgency/Value:3+' => 'Середня',
	'Class:UserRequest/Attribute:urgency/Value:4' => 'Низька',
	'Class:UserRequest/Attribute:urgency/Value:4+' => 'Низька',
	'Class:UserRequest/Attribute:origin' => 'Джерело',
	'Class:UserRequest/Attribute:origin+' => '~~',
	'Class:UserRequest/Attribute:origin/Value:mail' => 'Пошта',
	'Class:UserRequest/Attribute:origin/Value:mail+' => 'Пошта',
	'Class:UserRequest/Attribute:origin/Value:monitoring' => 'Моніторинг',
	'Class:UserRequest/Attribute:origin/Value:monitoring+' => 'Моніторинг',
	'Class:UserRequest/Attribute:origin/Value:phone' => 'Телефон',
	'Class:UserRequest/Attribute:origin/Value:phone+' => 'Телефон',
	'Class:UserRequest/Attribute:origin/Value:portal' => 'Портал',
	'Class:UserRequest/Attribute:origin/Value:portal+' => 'Портал',
	'Class:UserRequest/Attribute:approver_id' => 'Погоджувач',
	'Class:UserRequest/Attribute:approver_id+' => '~~',
	'Class:UserRequest/Attribute:approver_email' => 'Пошта погоджувача',
	'Class:UserRequest/Attribute:approver_email+' => '~~',
	'Class:UserRequest/Attribute:service_id' => 'Послуга',
	'Class:UserRequest/Attribute:service_id+' => '~~',
	'Class:UserRequest/Attribute:service_name' => 'Назва послуги',
	'Class:UserRequest/Attribute:service_name+' => '~~',
	'Class:UserRequest/Attribute:servicesubcategory_id' => 'Підкатегорія послуги',
	'Class:UserRequest/Attribute:servicesubcategory_id+' => '~~',
	'Class:UserRequest/Attribute:servicesubcategory_name' => 'Назва підкатегорії послуги',
	'Class:UserRequest/Attribute:servicesubcategory_name+' => '~~',
	'Class:UserRequest/Attribute:escalation_flag' => 'Порушення SLA',
	'Class:UserRequest/Attribute:escalation_flag+' => '~~',
	'Class:UserRequest/Attribute:escalation_flag/Value:no' => 'Ні',
	'Class:UserRequest/Attribute:escalation_flag/Value:no+' => 'Ні',
	'Class:UserRequest/Attribute:escalation_flag/Value:yes' => 'Так',
	'Class:UserRequest/Attribute:escalation_flag/Value:yes+' => 'Так',
	'Class:UserRequest/Attribute:escalation_reason' => 'Причина порушення SLA',
	'Class:UserRequest/Attribute:escalation_reason+' => '~~',
	'Class:UserRequest/Attribute:assignment_date' => 'Дата призначення',
	'Class:UserRequest/Attribute:assignment_date+' => '~~',
	'Class:UserRequest/Attribute:resolution_date' => 'Дата виконання',
	'Class:UserRequest/Attribute:resolution_date+' => '~~',
	'Class:UserRequest/Attribute:last_pending_date' => 'Дата призупинення',
	'Class:UserRequest/Attribute:last_pending_date+' => '~~',
	'Class:UserRequest/Attribute:cumulatedpending' => 'Загальний час зупинок',
	'Class:UserRequest/Attribute:cumulatedpending+' => 'Загальний накопичений час призупинення',
	'Class:UserRequest/Attribute:tto' => 'TTO',
	'Class:UserRequest/Attribute:tto+' => '(Time To Own) час на призначення виконавця',
	'Class:UserRequest/Attribute:ttr' => 'TTR',
	'Class:UserRequest/Attribute:ttr+' => '(Time To Resolve) час на виконання запиту',
	'Class:UserRequest/Attribute:tto_escalation_deadline' => 'Строк TTO',
	'Class:UserRequest/Attribute:tto_escalation_deadline+' => '~~',
	'Class:UserRequest/Attribute:sla_tto_passed' => 'SLA tto минуло',
	'Class:UserRequest/Attribute:sla_tto_passed+' => '~~',
	'Class:UserRequest/Attribute:sla_tto_over' => 'SLA tto перевищено',
	'Class:UserRequest/Attribute:sla_tto_over+' => '~~',
	'Class:UserRequest/Attribute:ttr_escalation_deadline' => 'Строк TTR',
	'Class:UserRequest/Attribute:ttr_escalation_deadline+' => '~~',
	'Class:UserRequest/Attribute:sla_ttr_passed' => 'SLA ttr минуло',
	'Class:UserRequest/Attribute:sla_ttr_passed+' => '~~',
	'Class:UserRequest/Attribute:sla_ttr_over' => 'SLA ttr перевищено',
	'Class:UserRequest/Attribute:sla_ttr_over+' => '~~',
	'Class:UserRequest/Attribute:time_spent' => 'Час виконання',
	'Class:UserRequest/Attribute:time_spent+' => '~~',
	'Class:UserRequest/Attribute:resolution_code' => 'Спосіб вирішення',
	'Class:UserRequest/Attribute:resolution_code+' => '~~',
	'Class:UserRequest/Attribute:resolution_code/Value:assistance' => 'Допомога',
	'Class:UserRequest/Attribute:resolution_code/Value:assistance+' => 'Допомога',
	'Class:UserRequest/Attribute:resolution_code/Value:bug fixed' => 'Виправлення помилки',
	'Class:UserRequest/Attribute:resolution_code/Value:bug fixed+' => 'Виправлення помилки',
	'Class:UserRequest/Attribute:resolution_code/Value:hardware repair' => 'Ремонт обладнання',
	'Class:UserRequest/Attribute:resolution_code/Value:hardware repair+' => 'Ремонт обладнання',
	'Class:UserRequest/Attribute:resolution_code/Value:other' => 'Інше',
	'Class:UserRequest/Attribute:resolution_code/Value:other+' => 'Інше',
	'Class:UserRequest/Attribute:resolution_code/Value:software patch' => 'Патч ПЗ',
	'Class:UserRequest/Attribute:resolution_code/Value:software patch+' => 'Патч ПЗ',
	'Class:UserRequest/Attribute:resolution_code/Value:system update' => 'Оновлення системи',
	'Class:UserRequest/Attribute:resolution_code/Value:system update+' => 'Оновлення системи',
	'Class:UserRequest/Attribute:resolution_code/Value:training' => 'Навчання',
	'Class:UserRequest/Attribute:resolution_code/Value:training+' => 'Навчання',
	'Class:UserRequest/Attribute:solution' => 'Опис рішення',
	'Class:UserRequest/Attribute:solution+' => '',
	'Class:UserRequest/Attribute:pending_reason' => 'Причина призупинки',
	'Class:UserRequest/Attribute:pending_reason+' => '',
	'Class:UserRequest/Attribute:parent_request_id' => 'Основний запит',
	'Class:UserRequest/Attribute:parent_request_id+' => '',
	'Class:UserRequest/Attribute:parent_request_ref' => 'Основний запит',
	'Class:UserRequest/Attribute:parent_request_ref+' => '',
	'Class:UserRequest/Attribute:parent_problem_id' => 'Основна проблема',
	'Class:UserRequest/Attribute:parent_problem_id+' => '',
	'Class:UserRequest/Attribute:parent_problem_ref' => 'Основна проблема',
	'Class:UserRequest/Attribute:parent_problem_ref+' => '~~',
	'Class:UserRequest/Attribute:parent_change_id' => 'Основна зміна',
	'Class:UserRequest/Attribute:parent_change_id+' => '~~',
	'Class:UserRequest/Attribute:parent_change_ref' => 'Основна зміна',
	'Class:UserRequest/Attribute:parent_change_ref+' => '~~',
	'Class:UserRequest/Attribute:related_request_list' => 'Пов’язані запити',
	'Class:UserRequest/Attribute:related_request_list+' => 'Усі дочірні запити',
	'Class:UserRequest/Attribute:public_log' => 'Загальний журнал',
	'Class:UserRequest/Attribute:public_log+' => 'Інформація загольного журналу доступна для користувачів порталу',
	'Class:UserRequest/Attribute:user_satisfaction' => 'Задоволеність користувача',
	'Class:UserRequest/Attribute:user_satisfaction+' => '~~',
	'Class:UserRequest/Attribute:user_satisfaction/Value:1' => 'Дуже задоволений',
	'Class:UserRequest/Attribute:user_satisfaction/Value:1+' => 'Дуже задоволений',
	'Class:UserRequest/Attribute:user_satisfaction/Value:2' => 'Задоволений',
	'Class:UserRequest/Attribute:user_satisfaction/Value:2+' => 'Задоволений',
	'Class:UserRequest/Attribute:user_satisfaction/Value:3' => 'Незадоволений',
	'Class:UserRequest/Attribute:user_satisfaction/Value:3+' => 'Незадоволений',
	'Class:UserRequest/Attribute:user_satisfaction/Value:4' => 'Дуже незадоволений',
	'Class:UserRequest/Attribute:user_satisfaction/Value:4+' => 'Дуже незадоволений',
	'Class:UserRequest/Attribute:user_comment' => 'Коментар користувача',
	'Class:UserRequest/Attribute:user_comment+' => '~~',
	'Class:UserRequest/Attribute:parent_request_id_friendlyname' => 'Основний запит',
	'Class:UserRequest/Attribute:parent_request_id_friendlyname+' => '~~',
	'Class:UserRequest/Stimulus:ev_assign' => 'Призначити',
	'Class:UserRequest/Stimulus:ev_assign+' => '~~',
	'Class:UserRequest/Stimulus:ev_reassign' => 'Призначити іншому',
	'Class:UserRequest/Stimulus:ev_reassign+' => '~~',
	'Class:UserRequest/Stimulus:ev_approve' => 'Погодити',
	'Class:UserRequest/Stimulus:ev_approve+' => '~~',
	'Class:UserRequest/Stimulus:ev_reject' => 'Відхилити',
	'Class:UserRequest/Stimulus:ev_reject+' => '~~',
	'Class:UserRequest/Stimulus:ev_pending' => 'Призупинити',
	'Class:UserRequest/Stimulus:ev_pending+' => '~~',
	'Class:UserRequest/Stimulus:ev_timeout' => 'Таймаут',
	'Class:UserRequest/Stimulus:ev_timeout+' => '~~',
	'Class:UserRequest/Stimulus:ev_autoresolve' => 'Автоматичне виконання',
	'Class:UserRequest/Stimulus:ev_autoresolve+' => '~~',
	'Class:UserRequest/Stimulus:ev_autoclose' => 'Автоматичне закриття',
	'Class:UserRequest/Stimulus:ev_autoclose+' => '~~',
	'Class:UserRequest/Stimulus:ev_resolve' => 'Позначити як виконаний',
	'Class:UserRequest/Stimulus:ev_resolve+' => '~~',
	'Class:UserRequest/Stimulus:ev_close' => 'Закрити запит',
	'Class:UserRequest/Stimulus:ev_close+' => '~~',
	'Class:UserRequest/Stimulus:ev_reopen' => 'Відкрити повторно',
	'Class:UserRequest/Stimulus:ev_reopen+' => '~~',
	'Class:UserRequest/Stimulus:ev_wait_for_approval' => 'На погодженні',
	'Class:UserRequest/Stimulus:ev_wait_for_approval+' => '~~',
	'Class:UserRequest/Error:CannotAssignParentRequestIdToSelf' => 'Неможливо пов’язати запист із самим собою',
));


Dict::Add('uk ua', 'Ukraine', 'Українська', array(
	'Portal:TitleDetailsFor_Request' => 'Детальна інформація',
	'Portal:ButtonUpdate' => 'Оновити',
	'Portal:ButtonClose' => 'Закрити',
	'Portal:ButtonReopen' => 'Відкрити повторно',
	'Portal:ShowServices' => 'Каталог послуг',
	'Portal:SelectRequestType' => 'Оберіть тип запиту',
	'Portal:SelectServiceElementFrom_Service' => 'Оберіть елемент послуги для %1$s~~',
	'Portal:ListServices' => 'Список послуг',
	'Portal:TitleDetailsFor_Service' => 'Інформація про послугу',
	'Portal:Button:CreateRequestFromService' => 'Створити запит на послугу',
	'Portal:ListOpenRequests' => 'Список відкритих запитів',
	'Portal:UserRequest:MoreInfo' => 'Додаткова інформація',
	'Portal:Details-Service-Element' => 'Елементи послуги',
	'Portal:NoClosedTicket' => 'Відсутні закриті запити',
	'Portal:NoService' => '~~',
	'Portal:ListOpenProblems' => 'Список відкритих проблем',
	'Portal:ShowProblem' => 'Проблеми',
	'Portal:ShowFaqs' => 'ЧаПи (часті/поширені питання)',
	'Portal:NoOpenProblem' => 'Відсутні відкриті проблеми',
	'Portal:SelectLanguage' => "Змінити мову",
	'Portal:LanguageChangedTo_Lang' => 'Змінити мову на',
	'Portal:ChooseYourFavoriteLanguage' => 'Оберіть мову',

	'Class:UserRequest/Method:ResolveChildTickets' => 'Виконати пов’язані запити',
	'Class:UserRequest/Method:ResolveChildTickets+' => 'Виконати рішення пов’язаних підлеглих запитів із встановленням наступних параметрів: послуга, команда, виконавець',
));


Dict::Add('uk ua', 'Ukraine', 'Українська', array(
	'Organization:Overview:UserRequests' => 'Запити користувачів цієї організації',
	'Organization:Overview:MyUserRequests' => 'Мої запити цієї організації',
	'Organization:Overview:Tickets' => 'Тікети цієї організації',
));
